### ISSUE TITLE
pinpoint backend on kubernetes clusters

### ISSUE THREAD

**Issue by goosetapa** [dawidmalina/docker-pinpoint#4]
@dawidmalina I have forked your docker-pinpoint and tried to run pinpoint backend and the sample app (rancher) on a k8s cluster. https://github.com/proddam/docker-pinpoint

I used [kompose](http://kompose.io/) to convert the docker-compose.yml to k8s manifest yamls. But no luck so far.  Of course your docker-compose.yml worked well on docker.  I think there are some connection issues between pinpoint modules when I run hbase, collector and agent on k8s.

Do you have any suggestion or solution for running pinpoint backend on k8s?

**Comment by dawidmalina** [comment]
It should work exactly the same. To be honest i didn't try to run pinpoint on kubernetes. Can you share your manifest?

**Comment by goosetapa** [comment]
Thank you for your prompt response. You can find the k8s manifest files in `k8s` folder at https://github.com/proddam/docker-pinpoint. I really appreciate your help.

**Comment by dawidmalina** [comment]
I just run your k8s manifests on my local claster:
```
[kubernetes-master] davidmal@stackperftestk8smaster0:~$ kubectl get pods
NAME                                  READY     STATUS    RESTARTS   AGE
pinpoint-collector-596748b987-zmkxn   1/1       Running   0          8m
pinpoint-hbase-6fb5fc7dcd-6ptlt       1/1       Running   0          11m
pinpoint-web-5c4cbd8cb7-s4cpw         1/1       Running   0          5m
rancher-server-59c94444b-56bnq        1/1       Running   0          3m
```

All was successfully started. What i did i started them in sequence as you see on the age column.
